// Code generated by sqlc. DO NOT EDIT.

package api

import (
	"database/sql"

	"github.com/google/uuid"
)

type Task struct {
	ID         uuid.UUID      `json:"id"`
	Command    sql.NullString `json:"command"`
	StartedAt  sql.NullTime   `json:"startedAt"`
	FinishedAt sql.NullTime   `json:"finishedAt"`
	Status     sql.NullString `json:"status"`
	Stdout     sql.NullString `json:"stdout"`
	Stderr     sql.NullString `json:"stderr"`
	ExitCode   sql.NullInt32  `json:"exitCode"`
}
